### ISSUE TITLE
cant reach device

### ISSUE THREAD

**Issue by felipebm1996** [roboception/rcdiscover#13]
Im using a virtual machine (ubuntu 20.04) to acquire data of rc_visard 160c.
I did the steps to setup the link local connection. Install the rcdiscover-gui and recognize the device (ip address, mac, name) but it is not reachable. Do you know how can fix this?

**Comment by flixr** [comment]
That depends on how you setup the virtual machine, so which IP/subnet it has to the outside..
In the rcdiscover GUI it should show the IP address of the rc_visard. Is that in the same subnet as your interface?
Then it should be "reachable" and you should be able to ping it and open the WebGUI...
Often it is a bit easier if you have a DHCP server running (e.g. on your router) and connect the rc_visard to the same network as you PC/Laptop instead of connecting it directly via link local or static IP in the same subnet.

**Comment by flixr** [comment]
Solution is to make sure the virtual network interface of the VM uses bridge mode:
e.g. https://www.virtualbox.org/manual/ch06.html#network_bridged
