### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by alicera** [roboception/rcdiscover#9]
I try to install the deb with double click
And it show the message
apt transaction returned result exit-failed

**Comment by flixr** [comment]
Could you please provide more details?
What OS/version are you running, which deb did you try to install, what was the error message, etc?

**Comment by alicera** [comment]
I use the ubuntu 16.04
git clone https://github.com/roboception/rcdiscover
cmake -DCMAKE_INSTALL_PREFIX="/usr" ..
make package

Then it will generate the deb in the build and I install it with double click.
Does your deb will auto install the dependencies lib (like apt install...）？

**Comment by flixr** [comment]
Which deb did you try to install?
It will generate two: rcdiscover and rcdiscover-dev.
rcdiscover-dev depends on rcdiscover, so if you want to install them manually, you need to install them both at the same time or rcdiscover first.

**Comment by alicera** [comment]
Do you know how to trigger the install with only using rcdiscover-dev？
rcdiscover-dev trigger the rcdiscover.

**Comment by flixr** [comment]
I never use the graphical installer, but you can just install both packages with `sudo dpkg -i *.deb` at the same time.
The -dev package only contains the headers, so you only need it if you want to link against the rcdiscover library.
If you only want the commandline tool, you don't need to install the -dev package.

**Comment by alicera** [comment]
Can the comand sudo dpkg -i *.deb  only use once？
 sudo dpkg -i A.deb, it will do the sudo dpkg -i B.deb at the same time.

**Comment by flixr** [comment]
Sorry, I don't quite understand what you're trying to say...

You can install multiple deb packages at the same time with dpkg. Assuming your are in the `build` dir where the deb files were created with `make package`:
`sudo dpkg -i *.deb` will install all deb packages in the current directory (since the your shell will expand the `*.deb` to all files ending with .deb).
For dpkg see also https://manpages.ubuntu.com/manpages/xenial/en/man1/dpkg.1.html

If you just want the commandline tool, you can also run `sudo dpkg -i rcdiscover_*.deb` or just double click on that one and use the graphical tool.

**Comment by alicera** [comment]
how to clear the 
 rcdiscover
 rcdiscover-dev
E: Sub-process /usr/bin/dpkg returned an error code (1)

I install rcdiscover and it fail. Now it affect my system to install any lib.
I just command  sudo apt install nodejs-legacy then it show the dpkg: error processing package rcdiscover-dev (--configure):

**Comment by heikohimu** [comment]
Removing packages under Ubuntu can be done by 'sudo apt purge'. For removing all rcdiscover packages type:
sudo apt purge rcdiscover*
